# Generated by Django 4.1.3 on 2022-11-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_location_alter_user_mob_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.IntegerField(default=0),
        ),
    ]
